<?php

namespace Jbl\StudioBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * WeekRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WeekRepository extends EntityRepository
{
	
	public function getByDate(\Datetime $date1, \Datetime $date2) {
		
		$queryBuilder = $this->createQueryBuilder('a');
		$queryBuilder->where('a.start > :date2 OR a.end > :date1')
					->setParameter('date1', $date1->format('Y-m-d'))
					->setParameter('date2', $date2->format('Y-m-d'));
		
		$query = $queryBuilder->getQuery();

		return $query->getResult();
	}
	
	public function getByTimestamp($timestamp1, $timestamp2) {
		return $this->getByDate(new \Datetime(date('Y-m-d', $timestamp1)),new \Datetime(date('Y-m-d', $timestamp2)));
	}	
	
	public function findByStartTimestamp($timestamp) {
		
		$startDatetime = new \Datetime(date('Y-m-d', $timestamp));
		$week = $this->findOneByStart($startDatetime->format('Y-m-d'));
		return $week;
	}
}